USE [master]
GO

/****** Object:  Database [HotelReservation]    Script Date: 6/30/2017 12:32:09 PM ******/
DROP DATABASE [HotelReservation]
GO

/****** Object:  Database [HotelReservation]    Script Date: 6/30/2017 12:32:09 PM ******/
CREATE DATABASE [HotelReservation]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'HotelReservation', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\HotelReservation.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'HotelReservation_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\HotelReservation_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [HotelReservation] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [HotelReservation].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [HotelReservation] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [HotelReservation] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [HotelReservation] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [HotelReservation] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [HotelReservation] SET ARITHABORT OFF 
GO

ALTER DATABASE [HotelReservation] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [HotelReservation] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [HotelReservation] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [HotelReservation] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [HotelReservation] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [HotelReservation] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [HotelReservation] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [HotelReservation] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [HotelReservation] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [HotelReservation] SET  ENABLE_BROKER 
GO

ALTER DATABASE [HotelReservation] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [HotelReservation] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [HotelReservation] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [HotelReservation] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [HotelReservation] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [HotelReservation] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [HotelReservation] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [HotelReservation] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [HotelReservation] SET  MULTI_USER 
GO

ALTER DATABASE [HotelReservation] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [HotelReservation] SET DB_CHAINING OFF 
GO

ALTER DATABASE [HotelReservation] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [HotelReservation] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [HotelReservation] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [HotelReservation] SET QUERY_STORE = OFF
GO

USE [HotelReservation]
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [HotelReservation] SET  READ_WRITE 
GO

